version: "2"

volumes:
  db-data:
    external: false

services:
  cache:
    image: memcached:1.4-alpine

  db:
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
    image: postgres:9.5
    volumes:
      - db-data:/usr/local/pgsql/data

  jobs:
    env_file: .env
    build: .
    volumes:
      - .:/usr/src/app
    command: bundle exec rake jobs:work
    depends_on:
      - db

  app:
    env_file: .env
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - "7000:8080"
    depends_on:
      - db
